version: '3'


services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - "5431:5432"
      
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: citasDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - postgres
